### ISSUE TITLE
MPI comm error

### ISSUE THREAD

**Issue by drtloudon** [jorgensd/mesh_converter#3]
Following your example, when I try to write an exodus mesh to xdmf format using the write_mesh function, I get the following error:

TypeError                                 Traceback (most recent call last)
<ipython-input-4-ac7b7f08ea9a> in <module>
----> 1 write_mesh(mesh_in, 'quarter_shell_tet.xdmf')

~/.local/lib/python3.10/site-packages/mesh_converter/writer.py in write_mesh(mesh, filename)
    146     # Create ADIOS2 reader
    147     assert MPI.COMM_WORLD.size == 1, "Mesh convert only works in serial for now"
--> 148     adios = adios2.ADIOS(MPI.COMM_WORLD)
    149     io = adios.DeclareIO("Mesh writer")
    150     io.SetEngine("HDF5")

TypeError: __init__(): incompatible constructor arguments. The following argument types are supported:
    1. adios2.bindings.adios2_bindings.ADIOS()
    2. adios2.bindings.adios2_bindings.ADIOS(configFile: str)

Invoked with: <mpi4py.MPI.Intracomm object at 0x7f8aaf4bf780>

I created a conda environment and downloaded the dependencies as you suggest.

**Comment by jorgensd** [comment]
This indicates that adios2 has not been installed with MPI support, as shown with the command:
```
conda install -c conda-forge adios2=*=mpi_* mpich mpi4py netcdf4
```
Please list the exact commands you ran, and the full traceback/output of this command.

**Comment by drtloudon** [comment]
The conda environment I created was loading an external adios2 package. Once I fixed that, I'm able to use the write_mesh function without error. However, when I go to load the created xdmf mesh inside dolfinx using:

from dolfinx import io
from mpi4py import MPI
with io.XDMFFile(MPI.COMM_WORLD, 'quarter_shell_tet.xdmf', 'r') as file:
    mesh = file.read_mesh(name='Grid')

I get the error:

Traceback (most recent call last):
  File "/home/tloudon/Research/Elasticity/ShearLocking/test.py", line 3, in <module>
    with io.XDMFFile(MPI.COMM_WORLD, 'quarter_shell_tet.xdmf', 'r') as file:
RuntimeError: Empty <Xdmf> root node.

Any help is appreciated. Thanks.

**Comment by jorgensd** [comment]
Please add the contents of the xdmf file here

**Comment by drtloudon** [comment]
The contents of quarter_shell_tet.xdmf are

```
<?xml version="1.0"?>
<!DOCTYPE Xdmf SYSTEM "Xdmf.dtd" []>
<XDMF Version="3.0" xmlns:xi="http://www.w3.org/2001/XInclude"><Domain><Grid GridType="Uniform" Name="Mesh"><Topology NumberOfElements="4399" TopologyType="Tetrahedron" NodesPerElement="4"><DataItem Dimensions="4399 4" Format="HDF">quarter_shell_tet.h5:/Step0/Connectivity_tetra</DataItem></Topology><Geometry GeometryType="XYZ"><DataItem Dimensions="1615 3" Format="HDF">quarter_shell_tet.h5:/Step0/Points</DataItem></Geometry><Attribute Name="Cell markers" AttributeType="Scalar" Center="Cell"><DataItem Dimensions="4399" Format="HDF" DataType="Int">quarter_shell_tet.h5:/Step0/Cell_Markers</DataItem></Attribute></Grid><Grid GridType="Uniform" Name="Facet_Mesh"><Topology NumberOfElements="3220" TopologyType="Triangle" NodesPerElement="3"><DataItem Dimensions="3220 3" Format="HDF">quarter_shell_tet.h5:/Step0/Connectivity_triangle</DataItem></Topology><Geometry GeometryType="XYZ"><DataItem Dimensions="1615 3" Format="HDF">quarter_shell_tet.h5:/Step0/Points</DataItem></Geometry><Attribute Name="Facet markers" AttributeType="Scalar" Center="Cell"><DataItem Dimensions="3220" Format="HDF" DataType="Int">quarter_shell_tet.h5:/Step0/Facet_Markers</DataItem></Attribute></Grid></Domain></XDMF>
```

**Comment by jorgensd** [comment]
That looks ok to me. Could you try to open it in paraview and see if it looks ok?

could you Also try:
`read_mesh(name="Mesh")` or is it opening the file that fails?

**Comment by drtloudon** [comment]
It's opening the file that throws the error. I can modify the code to:

```
from dolfinx import io
from mpi4py import MPI
file = io.XDMFFile(MPI.COMM_WORLD, 'quarter_shell_tet.xdmf', 'r')
```
and get the error. I put name='Grid' because previously I've used meshio where 'Grid' was the default name. Everything looks normal in Paraview. Even if I remove the facet blocks from the exodus file before converting to xdmf, I still get the same empty root node error.

**Comment by jorgensd** [comment]
That’s weird. Could you provide the xdmf and h5 file somewhere? Then I can run it tomorrow.

**Comment by drtloudon** [comment]
I emailed them to you. Not sure what the "accepted" method for sharing files is. Thanks again for your help.

**Comment by jorgensd** [comment]
Got the email. Will have a look tomorrow or sometime this weekend.

**Comment by jorgensd** [comment]
@drtloudon I've pushed a fix for the issue. Turns out DOLFINx has specific caps dependencies on the root note "Xdmf", which I initally wrote as "XDMF", as it works with Paraview.

**Comment by drtloudon** [comment]
Thanks for your help.
